/* SPDX-License-Identifier: GPL-3.0-or-later */

#ifndef KERNEL_ARCH_ARM64_ARCH_LAYOUT_H
#define KERNEL_ARCH_ARM64_ARCH_LAYOUT_H

#include "proc/init_layout.h"

#define ARCH_HEAP_START 0x01800000u
#define ARCH_HEAP_END 0x01F00000u

#define ARCH_USER_VADDR_MIN ARM64_INIT_IMAGE_BASE
#define ARCH_USER_VADDR_MAX ARM64_INIT_STACK_TOP
#define ARCH_USER_IMAGE_BASE ARM64_INIT_IMAGE_BASE
#define ARCH_USER_STACK_TOP ARM64_INIT_STACK_TOP
#define ARCH_USER_STACK_BASE ARM64_INIT_STACK_BASE
#define ARCH_USER_HEAP_MAX (ARCH_USER_STACK_BASE - 64u * 0x1000u)
#define ARCH_USER_MMAP_MIN 0x02400000u

#endif
