DOCS_SRC := docs/partI-firmware-to-kernel.md \
            docs/ch01-boot.md \
            docs/ch02-protected-mode.md \
            docs/ch03-kernel-entry.md \
            docs/ch04-interrupts.md \
            docs/ch05-irq-dispatch.md \
            docs/ch06-sse.md \
            docs/partII-memory.md \
            docs/ch07-memory-detection.md \
            docs/ch08-memory-management.md \
            docs/partIII-hardware-interfaces.md \
            docs/ch09-klog.md \
            docs/ch10-keyboard.md \
            docs/ch11-ata-disk.md \
            docs/ch12-device-registries.md \
            docs/partIV-files-and-storage.md \
            docs/ch13-filesystem.md \
            docs/ch14-vfs.md \
            docs/partV-running-user-programs.md \
            docs/ch15-processes.md \
            docs/ch16-syscalls.md \
            docs/ch17-file-io.md \
            docs/partVI-user-environment.md \
            docs/ch18-tty.md \
            docs/ch19-signals.md \
            docs/ch20-user-runtime.md \
            docs/ch21-libc.md \
            docs/ch22-shell.md \
            docs/partVII-extending-the-kernel.md \
            docs/ch23-modules.md \
            docs/ch24-core-dumps.md \
            docs/partVIII-fault-driven-memory.md \
            docs/ch25-demand-paging.md \
            docs/ch26-copy-on-write-fork.md \
            docs/partIX-graphical-environment.md \
            docs/ch27-mouse.md \
            docs/ch28-desktop.md \
            docs/partX-development-tools.md \
            docs/ch29-debugging.md \
            docs/ch30-cpp-userland.md \
            docs/ch31-aarch64-bringup.md
